-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  role text default 'student' check (role in ('student', 'admin')),
  student_id text unique,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Create a table for resources
create table resources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  type text not null, -- 'Tutorial', 'Video', 'Past Paper', etc.
  course text,
  url text not null, -- URL to file in storage or external link
  uploader_id uuid references auth.users not null,
  downloads integer default 0
);

alter table resources enable row level security;

create policy "Resources are viewable by everyone." on resources
  for select using (true);

create policy "Authenticated users can upload resources." on resources
  for insert with check ((select auth.uid()) = uploader_id);

create policy "Admins can update any resource." on resources
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Admins can delete any resource." on resources
  for delete using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for events
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  date timestamp with time zone not null,
  location text,
  category text,
  attendees_count integer default 0
);

alter table events enable row level security;

create policy "Events are viewable by everyone." on events
  for select using (true);

create policy "Admins can insert events." on events
  for insert with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Admins can update events." on events
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Admins can delete events." on events
  for delete using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for event rsvps
create table event_rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_id bigint references events on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  unique(event_id, user_id)
);

alter table event_rsvps enable row level security;

create policy "Users can view their own RSVPs." on event_rsvps
  for select using ((select auth.uid()) = user_id);

create policy "Authenticated users can RSVP." on event_rsvps
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can cancel their own RSVP." on event_rsvps
  for delete using ((select auth.uid()) = user_id);
